Repository team-baguni/baguni-be, pull requests merged in 2025-03, with the labels that each got.

#3 [FEAT] 테스트 계정 생성 / 로그인 API
  baguni-api/src/main/java/baguni/api/application/development/DevelopmentController.java
  baguni-api/src/main/java/baguni/api/service/user/service/UserService.java
  baguni-common/src/main/java/baguni/common/dto/NamePassword.java
  baguni-common/src/main/java/baguni/common/exception/error_code/UserErrorCode.java
  baguni-infra/src/main/java/baguni/infra/infrastructure/user/UserDataHandler.java
  baguni-infra/src/main/java/baguni/infra/infrastructure/user/UserRepository.java
  baguni-infra/src/main/java/baguni/infra/model/user/User.java
Labels: enhancement

#6 [FIX] /api/links 경로 GET만 허용
  baguni-api/src/main/java/baguni/security/config/SecurityConfig.java
Labels: bug

#7 [CHORE] bearer token 기반 테스트 유저 생성/조회 코드 삭제
  baguni-api/src/main/java/baguni/api/application/development/DevelopmentController.java
  baguni-api/src/main/java/baguni/api/config/SwaggerConfig.java
  baguni-api/src/main/java/baguni/api/service/user/service/UserService.java
  baguni-api/src/main/java/baguni/security/config/SecurityConfig.java
  baguni-api/src/main/java/baguni/security/filter/TestUserAuthenticationFilter.java
  baguni-infra/src/main/java/baguni/infra/infrastructure/user/UserDataHandler.java
  baguni-infra/src/main/java/baguni/infra/model/user/User.java
Labels: enhancement

#27 [FIX] 이슈 템플릿 수정
  .github/ISSUE_TEMPLATE/기능-개발-이슈-템플릿.md
  .github/ISSUE_TEMPLATE/버그-신고-이슈-템플릿.md
  .github/ISSUE_TEMPLATE/수정-이슈-템플릿.md
Labels: fix :fire:

#33 [REFACTOR] 셀레니움 리팩토링 및 본문 크롤링 하나로 통일
  baguni-batch/src/main/java/baguni/batch/domain/link/dto/LinkAnalyzeResult.java
  baguni-batch/src/main/java/baguni/batch/domain/link/service/LinkAnalyzer.java
  baguni-batch/src/main/java/baguni/batch/domain/link/service/LinkService.java
  baguni-common/src/main/java/baguni/common/config/OpenGraphConfig.java
  baguni-common/src/main/java/baguni/common/lib/opengraph/CrawlResult.java
  baguni-common/src/main/java/baguni/common/lib/opengraph/Metadata.java
  baguni-common/src/main/java/baguni/common/lib/opengraph/OpenGraphException.java
  baguni-common/src/main/java/baguni/common/lib/opengraph/OpenGraphReader.java
  baguni-common/src/main/java/baguni/common/lib/opengraph/OpenGraphReaderJsoup.java
  baguni-common/src/main/java/baguni/common/lib/opengraph/OpenGraphReaderSelenium.java
  baguni-common/src/main/java/baguni/common/lib/opengraph/SeleniumCrawler.java
  baguni-common/src/main/java/baguni/common/lib/opengraph/SeleniumException.java
  baguni-common/src/main/java/baguni/common/lib/opengraph/SeleniumOption.java
Labels: refactor :construction:

#36 [FEAT] llama3.2 본문 글 요약 기능
  baguni-batch/src/main/java/baguni/batch/config/FeedApiConfig.java
  baguni-batch/src/main/java/baguni/batch/config/MessageConverterConfig.java
  baguni-batch/src/main/java/baguni/batch/config/OllamaApiConfig.java
  baguni-batch/src/main/java/baguni/batch/config/XmlMapperConfig.java
  baguni-batch/src/main/java/baguni/batch/domain/feed/dto/LlamaRequest.java
  baguni-batch/src/main/java/baguni/batch/domain/feed/dto/LlamaResponse.java
  baguni-batch/src/main/java/baguni/batch/domain/feed/util/Llama32KoreanAgent.java
  baguni-batch/src/main/java/baguni/batch/domain/feed/util/OllamaApi.java
  baguni-batch/src/main/java/baguni/batch/domain/link/service/LinkService.java
  baguni-batch/src/test/java/baguni/batch/domain/feed/util/BlogExamples.java
  baguni-batch/src/test/java/baguni/batch/domain/feed/util/llama32KoreanAgentTest.java
  baguni-infra/src/main/java/baguni/infra/model/link/Link.java
Labels: feat :bulb:

#43 [FEAT] 테스트용 api 추가 (개별 링크)
  baguni-api/src/main/java/baguni/api/application/development/DevelopmentController.java
  baguni-batch/src/main/java/baguni/batch/domain/feed/util/Llama32KoreanAgent.java
Labels: feat :bulb:

#50 [HOTFIX] 개발 전용 api 버그 수정
  baguni-api/src/main/java/baguni/api/application/development/DevelopmentController.java
  baguni-infra/src/main/java/baguni/infra/model/link/Link.java
  docker-compose.yaml
Labels: bug :bug:

#52 [FIX] 날짜 갱신 로직 추가
  baguni-infra/src/main/java/baguni/infra/model/link/Link.java
Labels: fix :fire:

#48 [REFACTOR] gpt / llama 교체 가능하게 리팩토링
  baguni-batch/src/main/java/baguni/batch/config/OllamaApiConfig.java
  baguni-batch/src/main/java/baguni/batch/domain/analyzer/ArticleAnalyzer.java
  baguni-batch/src/main/java/baguni/batch/domain/analyzer/ollama/LlamaRequest.java
  baguni-batch/src/main/java/baguni/batch/domain/analyzer/ollama/LlamaResponse.java
  baguni-batch/src/main/java/baguni/batch/domain/analyzer/ollama/OllamaApi.java
  baguni-batch/src/main/java/baguni/batch/domain/analyzer/ollama/OllamaKoreanArticleAnalyzer.java
  baguni-batch/src/main/java/baguni/batch/domain/crawler/LinkCrawlResult.java
  baguni-batch/src/main/java/baguni/batch/domain/crawler/LinkCrawler.java
  baguni-batch/src/main/java/baguni/batch/domain/feed/util/Llama32KoreanAgent.java
  baguni-batch/src/main/java/baguni/batch/domain/link/service/LinkService.java
  baguni-batch/src/test/java/baguni/batch/domain/analyzer/ArticleAnalyzerTest.java
  baguni-batch/src/test/java/baguni/batch/domain/analyzer/BlogExamples.java
  baguni-batch/src/test/java/baguni/batch/domain/feed/util/llama32KoreanAgentTest.java
  baguni-batch/src/test/java/baguni/batch/domain/link/service/LinkServiceTest.java
Labels: refactor :construction:

#54 [FEAT] 카테고리 분석 프롬프트 구현
  baguni-batch/src/main/java/baguni/batch/domain/analyzer/ollama/OllamaKoreanArticleAnalyzer.java
  baguni-batch/src/test/java/baguni/batch/domain/analyzer/ArticleAnalyzerTest.java
  baguni-batch/src/test/java/baguni/batch/domain/analyzer/BlogExamples.java
Labels: feat :bulb:

#56 [FEAT] 링크 요약 및 카테고리 저장 기능
  baguni-batch/src/main/java/baguni/batch/domain/crawler/LinkCrawler.java
  baguni-batch/src/main/java/baguni/batch/domain/link/service/LinkService.java
  baguni-common/src/main/java/baguni/common/exception/error_code/LinkErrorCode.java
  baguni-infra/src/main/java/baguni/infra/infrastructure/link/LinkDataHandler.java
  baguni-infra/src/main/java/baguni/infra/infrastructure/link/LinkRepository.java
  baguni-infra/src/main/java/baguni/infra/infrastructure/link/dto/LinkCommand.java
Labels: feat :bulb:

#55 [CHORE] 링크 엔티티에 content, category 추가
  baguni-batch/src/main/java/baguni/batch/domain/crawler/LinkCrawler.java
  baguni-batch/src/main/java/baguni/batch/domain/link/service/LinkService.java
  baguni-common/src/main/java/baguni/common/exception/error_code/LinkErrorCode.java
  baguni-infra/src/main/java/baguni/infra/infrastructure/link/LinkDataHandler.java
  baguni-infra/src/main/java/baguni/infra/infrastructure/link/LinkRepository.java
  baguni-infra/src/main/java/baguni/infra/infrastructure/link/dto/LinkCommand.java
  baguni-infra/src/main/java/baguni/infra/infrastructure/link/dto/LinkResult.java
  baguni-infra/src/main/java/baguni/infra/model/link/Link.java
  baguni-infra/src/main/resources/db/migration/V5.1__add_link_content_category_.sql
Labels: chore :email:

#60 [FIX] 로그 추가 및 프롬프트 상수로 분리
  baguni-batch/src/main/java/baguni/batch/config/OllamaApiConfig.java
  baguni-batch/src/main/java/baguni/batch/domain/analyzer/ollama/OllamaKoreanArticleAnalyzer.java
  baguni-batch/src/main/java/baguni/batch/domain/analyzer/prompt/LlmPrompt.java
  baguni-batch/src/main/java/baguni/batch/domain/crawler/LinkCrawler.java
  baguni-batch/src/test/java/baguni/batch/domain/link/service/LinkServiceTest.java
Labels: fix :fire:

#62 [HOTFIX] 스케쥴 딜레이 변경, 에러 try catch 추가
  baguni-batch/src/main/java/baguni/batch/config/OllamaApiConfig.java
  baguni-batch/src/main/java/baguni/batch/domain/link/service/LinkService.java
Labels: bug :bug:

#63 [FIX] 링크 크롤링 관련 로그 추가, 에러 레벨 변경
  baguni-batch/src/main/java/baguni/batch/domain/crawler/LinkCrawler.java
  baguni-common/src/main/java/baguni/common/exception/error_code/LinkErrorCode.java
  baguni-common/src/main/java/baguni/common/lib/opengraph/SeleniumCrawler.java
Labels: fix :fire:

#64 [HOTFIX] 토큰 개수 출력 로그 추가
  baguni-batch/src/main/java/baguni/batch/domain/link/service/LinkService.java
Labels: bug :bug:

#65 [HOTFIX] Selenium 예외 레벨 변경, 주석 추가
  baguni-batch/src/main/java/baguni/batch/domain/link/service/LinkService.java
  baguni-common/src/main/java/baguni/common/lib/opengraph/SeleniumCrawler.java
Labels: fix :fire:

#66 [HOTFIX] Selenium StaleElementReferenceException 처리
  baguni-common/src/main/java/baguni/common/lib/opengraph/SeleniumCrawler.java
Labels: fix :fire:

#67 [FIX] p 태그 획득 시 retry 로직 추가
  baguni-common/src/main/java/baguni/common/lib/opengraph/SeleniumCrawler.java
Labels: fix :fire:

#68 [FIX] content 예외 발생 길이 조건 변경
  baguni-batch/src/main/java/baguni/batch/domain/crawler/LinkCrawler.java
Labels: fix :fire:

#71 [FEAT] AI 요약 작업 400자씩 나눠 요청
  baguni-batch/src/main/java/baguni/batch/config/OllamaApiConfig.java
  baguni-batch/src/main/java/baguni/batch/domain/ai/AiAgent.java
  baguni-batch/src/main/java/baguni/batch/domain/ai/PromptBuilder.java
  baguni-batch/src/main/java/baguni/batch/domain/ai/ollama/OllamaAgent.java
  baguni-batch/src/main/java/baguni/batch/domain/ai/ollama/OllamaApi.java
  baguni-batch/src/main/java/baguni/batch/domain/ai/ollama/OllamaRequest.java
  baguni-batch/src/main/java/baguni/batch/domain/ai/ollama/OllamaResponse.java
  baguni-batch/src/main/java/baguni/batch/domain/analyzer/AiArticleAnalyzer.java
  baguni-batch/src/main/java/baguni/batch/domain/analyzer/ollama/LlamaResponse.java
  baguni-batch/src/main/java/baguni/batch/domain/analyzer/ollama/OllamaKoreanArticleAnalyzer.java
  baguni-batch/src/main/java/baguni/batch/domain/analyzer/prompt/LlmPrompt.java
  baguni-batch/src/main/java/baguni/batch/domain/analyzer/util/SplitText.java
  baguni-batch/src/main/java/baguni/batch/domain/link/service/LinkService.java
  baguni-batch/src/test/java/baguni/batch/domain/analyzer/ArticleAnalyzerTest.java
  baguni-batch/src/test/java/baguni/batch/domain/analyzer/BlogExamples.java
Labels: feat :bulb:

#69 [REFCATOR] description 수정, content 공백 시 처리
  baguni-batch/src/main/java/baguni/batch/domain/crawler/LinkCrawler.java
Labels: refactor :construction:

#74 [FIX] Ollama Timeout 확인용 log 추가
  baguni-batch/src/main/java/baguni/batch/domain/ai/ollama/OllamaAgent.java
Labels: fix :fire:

#76 [FIX] 요약 프롬프트 수정 및 시간 추적 로그 추가
  baguni-batch/src/main/java/baguni/batch/domain/ai/PromptBuilder.java
  baguni-batch/src/main/java/baguni/batch/domain/ai/ollama/OllamaAgent.java
Labels: fix :fire:

#77 [REFACTOR] 문장 수로 자르지 않고 문장 마지막에 단어로 자르도록 변경
  baguni-batch/src/main/java/baguni/batch/domain/ai/ollama/OllamaAgent.java
  baguni-batch/src/main/java/baguni/batch/lib/SplitText.java
Labels: refactor :construction:

#75 [REFACTOR] 이미지 링크 유효성 검사
  baguni-api/src/main/java/baguni/api/application/link/controller/LinkApiController.java
  baguni-api/src/main/java/baguni/api/service/link/service/LinkService.java
  baguni-batch/src/main/java/baguni/batch/config/LinkApiConfig.java
  baguni-batch/src/main/java/baguni/batch/domain/link/service/LinkService.java
  baguni-batch/src/main/java/baguni/batch/domain/link/util/LinkApi.java
  baguni-batch/src/main/java/baguni/batch/listener/LinkUpdateEventListener.java
  baguni-batch/src/main/resources/application.yaml
  baguni-common/src/main/java/baguni/common/event/LinkCheckEvent.java
  baguni-infra/src/main/java/baguni/infra/infrastructure/link/LinkDataHandler.java
  baguni-infra/src/main/java/baguni/infra/infrastructure/link/dto/LinkCommand.java
Labels: refactor :construction:

#80 [FEAT] 링크 유효성 검사
  baguni-batch/src/main/java/baguni/batch/domain/link/service/LinkService.java
  baguni-batch/src/main/java/baguni/batch/domain/link/util/LinkApi.java
  baguni-batch/src/main/java/baguni/batch/listener/LinkUpdateEventListener.java
  baguni-batch/src/test/resources/application.yaml
  baguni-common/src/main/java/baguni/common/event/LinkCheckEvent.java
  baguni-infra/src/main/java/baguni/infra/infrastructure/link/LinkDataHandler.java
  baguni-infra/src/main/java/baguni/infra/infrastructure/link/dto/LinkCommand.java
  baguni-infra/src/main/java/baguni/infra/infrastructure/link/dto/LinkMapper.java
  baguni-infra/src/main/java/baguni/infra/infrastructure/link/dto/LinkResult.java
  baguni-infra/src/main/java/baguni/infra/model/link/Link.java
  baguni-infra/src/main/resources/db/migration/V5.2__add_link_is_valid_.sql
Labels: feat :bulb:

#81 [REFACTOR] LinkApi / FeedApi HttpInterface 하나로 병합
  baguni-batch/src/main/java/baguni/batch/config/FeedApiConfig.java
  baguni-batch/src/main/java/baguni/batch/config/VisitWebsiteApiConfig.java
  baguni-batch/src/main/java/baguni/batch/domain/ai/AiAgent.java
  baguni-batch/src/main/java/baguni/batch/domain/ai/Prompt.java
  baguni-batch/src/main/java/baguni/batch/domain/ai/ollama/OllamaAgent.java
  baguni-batch/src/main/java/baguni/batch/domain/analyzer/AiArticleAnalyzer.java
  baguni-batch/src/main/java/baguni/batch/domain/feed/FeedService.java
  baguni-batch/src/main/java/baguni/batch/domain/feed/util/FeedApi.java
  baguni-batch/src/main/java/baguni/batch/domain/link/LinkService.java
  baguni-batch/src/main/java/baguni/batch/domain/link/util/LinkApi.java
  baguni-batch/src/main/java/baguni/batch/lib/VisitWebsiteApi.java
  baguni-batch/src/main/java/baguni/batch/listener/LinkUpdateEventListener.java
  baguni-batch/src/test/java/baguni/batch/domain/feed/RssRetrieveTest.java
  baguni-batch/src/test/java/baguni/batch/domain/feed/service/FeedServiceTest.java
  baguni-batch/src/test/java/baguni/batch/domain/link/service/LinkServiceTest.java
Labels: refactor :construction:

#94 [FEAT] 카테고리 선정 방식 개선
  baguni-batch/src/main/java/baguni/batch/domain/ai/ollama/OllamaAgent.java
  baguni-batch/src/main/java/baguni/batch/domain/ai/ollama/OllamaChatRequestBuilder.java
  baguni-batch/src/main/java/baguni/batch/domain/analyzer/ArticleCategory.java
Labels: feat :bulb:

#93 [FIX] 프롬프트 결과에서 \\* 강조 제거
  baguni-batch/src/main/java/baguni/batch/domain/ai/ollama/OllamaAgent.java
  baguni-batch/src/main/java/baguni/batch/domain/ai/ollama/OllamaChatRequestBuilder.java
  baguni-batch/src/main/java/baguni/batch/domain/analyzer/ArticleCategory.java
Labels: fix :fire:

#92 [REFACTOR] LinkService에 AiAgent 변경사항 반영
  baguni-batch/src/main/java/baguni/batch/domain/ai/ollama/OllamaAgent.java
  baguni-batch/src/main/java/baguni/batch/domain/ai/ollama/OllamaChatRequestBuilder.java
  baguni-batch/src/main/java/baguni/batch/domain/ai/util/Prompt.java
  baguni-batch/src/main/java/baguni/batch/domain/analyzer/ArticleCategory.java
  baguni-batch/src/main/java/baguni/batch/domain/link/LinkService.java
  baguni-batch/src/main/java/baguni/batch/domain/validator/LinkValidator.java
Labels: refactor :construction:

#91 [FEAT] OllamaAgent 응답 포맷 강제
  baguni-batch/src/main/java/baguni/batch/domain/ai/AiAgent.java
  baguni-batch/src/main/java/baguni/batch/domain/ai/ollama/OllamaAgent.java
  baguni-batch/src/main/java/baguni/batch/domain/ai/ollama/OllamaApi.java
  baguni-batch/src/main/java/baguni/batch/domain/ai/ollama/OllamaChatRequestBuilder.java
  baguni-batch/src/main/java/baguni/batch/domain/ai/ollama/OllamaResponse.java
  baguni-batch/src/main/java/baguni/batch/domain/ai/ollama/dto/OllamaCategorizeResult.java
  baguni-batch/src/main/java/baguni/batch/domain/ai/ollama/dto/OllamaChatRequest.java
  baguni-batch/src/main/java/baguni/batch/domain/ai/ollama/dto/OllamaChatResponse.java
  baguni-batch/src/main/java/baguni/batch/domain/ai/ollama/dto/OllamaGenerateRequest.java
  baguni-batch/src/main/java/baguni/batch/domain/ai/ollama/dto/OllamaGenerateResponse.java
  baguni-batch/src/main/java/baguni/batch/domain/ai/ollama/dto/OllamaGetKeywordsResult.java
  baguni-batch/src/main/java/baguni/batch/domain/ai/ollama/dto/OllamaMessage.java
  baguni-batch/src/main/java/baguni/batch/domain/ai/ollama/dto/OllamaSubCategorizeResult.java
  baguni-batch/src/main/java/baguni/batch/domain/ai/ollama/dto/OllamaSummarizeResult.java
  baguni-batch/src/main/java/baguni/batch/domain/ai/util/Prompt.java
  baguni-batch/src/main/java/baguni/batch/domain/analyzer/ArticleCategory.java
  baguni-batch/src/main/java/baguni/batch/domain/analyzer/TextAnalyzable.java
  baguni-batch/src/main/java/baguni/batch/domain/link/LinkService.java
  baguni-batch/src/main/java/baguni/batch/domain/validator/LinkValidator.java
  baguni-batch/src/test/java/baguni/batch/domain/ai/AiAgentTest.java
Labels: feat :bulb:

#90 [REFACTOR] AiAnalyzer 클래스 리팩토링
  baguni-batch/src/main/java/baguni/batch/domain/ai/AiAgent.java
  baguni-batch/src/main/java/baguni/batch/domain/ai/ollama/OllamaAgent.java
  baguni-batch/src/main/java/baguni/batch/domain/ai/ollama/OllamaApi.java
  baguni-batch/src/main/java/baguni/batch/domain/ai/ollama/OllamaChatRequestBuilder.java
  baguni-batch/src/main/java/baguni/batch/domain/ai/ollama/OllamaResponse.java
  baguni-batch/src/main/java/baguni/batch/domain/ai/ollama/dto/OllamaCategorizeResult.java
  baguni-batch/src/main/java/baguni/batch/domain/ai/ollama/dto/OllamaChatRequest.java
  baguni-batch/src/main/java/baguni/batch/domain/ai/ollama/dto/OllamaChatResponse.java
  baguni-batch/src/main/java/baguni/batch/domain/ai/ollama/dto/OllamaGenerateRequest.java
  baguni-batch/src/main/java/baguni/batch/domain/ai/ollama/dto/OllamaGenerateResponse.java
  baguni-batch/src/main/java/baguni/batch/domain/ai/ollama/dto/OllamaGetKeywordsResult.java
  baguni-batch/src/main/java/baguni/batch/domain/ai/ollama/dto/OllamaMessage.java
  baguni-batch/src/main/java/baguni/batch/domain/ai/ollama/dto/OllamaSubCategorizeResult.java
  baguni-batch/src/main/java/baguni/batch/domain/ai/ollama/dto/OllamaSummarizeResult.java
  baguni-batch/src/main/java/baguni/batch/domain/ai/util/Prompt.java
  baguni-batch/src/main/java/baguni/batch/domain/analyzer/AiArticleAnalyzer.java
  baguni-batch/src/main/java/baguni/batch/domain/analyzer/AnalyzeResult.java
  baguni-batch/src/main/java/baguni/batch/domain/analyzer/ArticleAnalyzer.java
  baguni-batch/src/main/java/baguni/batch/domain/analyzer/ArticleCategory.java
  baguni-batch/src/main/java/baguni/batch/domain/analyzer/TextAnalyzable.java
  baguni-batch/src/main/java/baguni/batch/domain/link/LinkService.java
  baguni-batch/src/main/java/baguni/batch/domain/validator/LinkValidator.java
  baguni-batch/src/test/java/baguni/batch/domain/ai/AiAgentTest.java
  baguni-batch/src/test/java/baguni/batch/domain/analyzer/ArticleAnalyzerTest.java
Labels: refactor :construction:

#95 [TEST] 링크 분석 처리 테스트 로직 추가
  baguni-batch/src/main/java/baguni/batch/domain/link/LinkService.java
Labels: test :boom:

#99 [CHORE] summary 각 Chunk마다 개행 추가
  baguni-batch/src/main/java/baguni/batch/domain/analyzer/ArticleAnalyzer.java
  baguni-batch/src/main/java/baguni/batch/domain/link/LinkService.java
Labels: chore :email:

#100 [HOTFIX] 셀레니움, 링크 유효성 url 로그 추가
  baguni-batch/src/main/java/baguni/batch/domain/validator/LinkValidator.java
  baguni-common/src/main/java/baguni/common/lib/opengraph/SeleniumCrawler.java
Labels: fix :fire:

#103 [FIX] 링크 크롤링 + 분석 로직을 한 작업으로 묶음
  baguni-batch/src/main/java/baguni/batch/domain/link/LinkService.java
  baguni-batch/src/main/java/baguni/batch/domain/validator/LinkValidator.java
  baguni-infra/src/main/java/baguni/infra/model/link/Link.java
Labels: fix :fire:

#87 [FEAT] Blog / Article 도메인 엔티티 정의
  baguni-batch/src/main/java/baguni/batch/pojo/channel/Blog.java
  baguni-batch/src/main/java/baguni/batch/pojo/channel/BlogArticle.java
  baguni-batch/src/main/java/baguni/batch/pojo/channel/FeedSupportingBlog.java
  baguni-batch/src/main/java/baguni/batch/pojo/information/Information.java
  baguni-batch/src/main/java/baguni/batch/pojo/information/InformationCategory.java
  baguni-batch/src/main/java/baguni/batch/pojo/resource/WebImage.java
  baguni-batch/src/main/java/baguni/batch/pojo/resource/WebLink.java
Labels: design :art:
